[package]
name = "headlines"
version = "0.1.0"
edition = "2021"

[dependencies]
confy = "0.5.1"
eframe = "0.21.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
news_api = { path = "../news_api" }
serde = { version = "1.0.152", features = ["derive"] }